// OPTIONS: -g
module Bug1121
{
  Foo (index : int) : void {
    if (index == 3)
      throw System.ArgumentOutOfRangeException ()
    else
      throw System.ApplicationException ()
  }
  Main () : void
  {
    try {
      Foo (3)
    }
    catch {
      | _ is System.ArgumentOutOfRangeException => System.Console.WriteLine("OK");
    } 
  }
}
/*
BEGIN-OUTPUT
OK
END-OUTPUT
*/
