using System;

public class ExceptionWithAnonMethod
{
  public delegate EmptyCallback() :  void;
      static  mutable  res : string;
  
  public static Main() :  int
  {
    try {
      throw  Exception("e is afraid to enter anonymous land");
    } catch {
                  |  e is Exception =>  {
      AnonHandler(fun() {
        Console.WriteLine(e.Message); 
        res = e.Message;
      });
    } }
    if (res == "e is afraid to enter anonymous land")
    {{
        Console.WriteLine ("Test passed");
         0;
    }
    }
    else
  {
  {
    Console.WriteLine ("Test failed");
     1;
  }
  }
  }

  public static AnonHandler(mutable  handler : EmptyCallback) :  void
  {
    when(handler != null) {
      handler();
    }
  }
}

/*
BEGIN-OUTPUT
e is afraid to enter anonymous land  
Test passed  
END-OUTPUT
*/
