//
// This test does not pass peverify because we dont return properly
// from catch blocks
//
using System;

class X {

   v () : bool
  {
    _ = try {
      throw  Exception ();
    }
    catch { | _ =>  {
       false;
    }
    }
     true;
  }

  static Main () :  int
  {
     0;
  }   
}
/*
BEGIN-OUTPUT
END-OUTPUT
*/
