//
// Sample for bug 75674
//
using System;
using System.Collections;

class XX {
  static Metodo (mutable  e : Exception) :  void
  {
    if (e is NotImplementedException){
      Console.WriteLine ("OK");
    } else {
      Console.WriteLine ("Fail");
    }
  }
  
  static X () :  IEnumerable
  {
    try {
      throw  NotImplementedException ();
    } catch {  |  e is Exception => {
      Metodo (e);
    } }
    yield 0;
  }
  
  static Main () :  void
  {
    foreach ( _a :> int in X ()){
    }
  }
}

/*
BEGIN-OUTPUT
OK
END-OUTPUT
*/
